### ISSUE TITLE
There is a major issue with the Chinese translation.😨

### ISSUE THREAD

**Issue by okyan123** [huynhsontung/Screenbox#123] opened 2023-08-10 12:24 UTC
Hello again, it's me. Last month, I submitted the Chinese translation. A couple of days ago, I was thrilled to discover that you had released a new version with the Chinese translation included. However, upon launching the software, I encountered a rather significant issue. To put it simply, the Chinese translation was completely scrambled, or more precisely, the translations seemed to be displaced and appeared in incorrect places.

For example, here the {} is used in C# for string interpolation, hava a variable in between. However, this sentence is now in the wrong position, causing {} to remain unchanged.
![image](https://github.com/huynhsontung/Screenbox/assets/100983934/04b69b85-0c3a-4dc0-9ccc-5189456978e6)

Even the software's name is incorrect. The term 'AAC Audio', which represents the software name, has been placed in the wrong location and has even replaced the actual software name.
![image](https://github.com/huynhsontung/Screenbox/assets/100983934/6ccaf1af-29bd-4997-9861-014f2b362a96)

I'm currently taking a look at the version history to find out how to address this issue. Do you have any thoughts?😭

**Comment by okyan123** [comment] 2023-08-10 14:08
I just tried downloading the release's sideload.zip and installing it. I encountered the same issue, and when I tried to open the software for the second time, it crashed. I couldn't open it successfully. It seems like there's a somewhat serious issue going on.😨

**Comment by huynhsontung** [comment] 2023-08-10 17:46
Oh no I will take a look ASAP. I have no idea what would cause this. The store-publish package is built in a [CI pipeline](https://github.com/huynhsontung/Screenbox/actions/runs/5791953947). Maybe there is some misconfiguration with the CI? I will try to build locally and publish a hotfix later tonight.

**Comment by huynhsontung** [comment] 2023-08-10 19:34
Can you try this side load package instead? I just built it locally.
https://github.com/huynhsontung/Screenbox/releases/download/v0.9.9/Screenbox_0.9.9.0_Test.zip

**Comment by huynhsontung** [comment] 2023-08-11 05:43
Can confirm that the package from the store has the issue. I couldn't replicate it with the sideload package though. Uninstalling the store version then install the sideload and it works as expected.

**Comment by okyan123** [comment] 2023-08-11 06:14
Thank you. With the sideload version, I succeeded😄, but another issue arose. Here's the situation: I have two computers. Yesterday, on my main computer, I encountered this issue. Both the store and sideload versions had this issue. Even after uninstalling the store version and installing the sideload version, the Chinese translation still went wrong.

However, on my other computer, I never installed the store version. When I directly installed the sideload version, it worked successfully without any problems. 

So, indeed, the issue originates from the store version. And I also need to clean up some other things.

**Comment by okyan123** [comment] 2023-08-11 06:59
Success! I used a tool to clean up some files in the WindowsApps folder, then reinstalled the sideload version. Finally, it successfully ran on my main computer as well.

**Comment by huynhsontung** [comment] 2023-08-14 17:21
I found and fixed the issue in the latest version. It was an error in appx bundling that messed up the app resources. Fixed in #124 by disabling the ARM version bundling. The same issue seems to have affected #99 as well.

Confirmed the issue is resolved on my end with store version v0.9.11

**Closed** 2023-08-15 16:46 UTC
Labels: bug
