### ISSUE TITLE
Automatically add All Videos in the Directory to the Playlist

### ISSUE THREAD

**Issue by Abel-Demere** [huynhsontung/Screenbox#497] opened 2024-11-28 20:28 UTC
Currently, the player only switches to the next video and previous in the directory when I press the "Next" or "Previous" button and can only do this in a sequential order. To play a video not loaded previously or out of order, I have to go back to the file explorer and manually select the desired video, which disrupts my viewing experience.

I would like the Screen Box player to automatically load all video files within a directory into a playlist when starting playback. This would allow me to easily navigate between videos, skip episodes, or play videos in any order without needing to manually access the file explorer each time.

I have considered using other video players that offer this feature, but I prefer the interface and functionality of Screen Box. Additionally, I have tried manually creating playlists in the file explorer, but this is cumbersome and not as convenient as having the player do it automatically.

This feature would greatly enhance the user experience by providing more flexibility and ease of use. It would be particularly beneficial for users who watch series or multiple videos in the same folder.

Thank you for considering this suggestion!

**Comment by United600** [comment] 2024-11-28 22:16
> I would like the Screen Box player to automatically load all video files within a directory into a playlist when starting playback. This would allow me to easily navigate between videos, skip episodes, or play videos in any order without needing to manually access the file explorer each time.

If you open a video using the 'Videos' navigation item in the app, it will add all files within that directory (or all videos if using the 'All Videos' item) to the play queue.

**Comment by huynhsontung** [comment] 2024-11-29 05:51
When you want the whole directory to be loaded in the playlist, you can select all files in that directory, right click and select open with Screenbox. The app will load all valid media files into the playlist. Is this a good solution for you?

**Comment by Abel-Demere** [comment] 2024-11-29 14:36
Thanks for the suggestion! I know this might be a bit of a lazy request, but I’ve just gotten so used to media players like MPC or PotPlayer, where opening a single file automatically adds all the files in the folder to the playlist. They have a setting to enable this behavior. It would be a great quality-of-life feature if Screenbox could do the same. I really appreciate your consideration of this idea, and I hope it might be something to look into for future updates!

**Comment by huynhsontung** [comment] 2024-12-21 20:25
Potential duplicate of #441

**Closed** 2024-12-31 08:23 UTC
Labels: enhancement

**Comment by Abel-Demere** [comment] 2025-01-12 20:56
<img width="655" alt="Screenshot 2025-01-12 233721" src="https://github.com/user-attachments/assets/0ab6bc75-5d2c-43eb-bbbb-ca7e30cb7196" />

Thanks for the update! I just noticed the new feature and it works perfectly. This will make using Screenbox so much more convenient. Your quick response and attention to user feedback are truly appreciated.

Keep up the great work!
