### ISSUE TITLE
Constant crashing on version 14.2

### ISSUE THREAD

**Issue by RoyceThomas** [huynhsontung/Screenbox#502] opened 2024-12-04 08:13 UTC
cant open v14.2 of the app on my pc, so i had to manually install 14.1 back from github.com/huynhsontung/Screenbox/releases. ive tried installing both from ms store, msic bundles and resetting the app from settings 
fortunately (or unfortunately) i can reproduce this event on my pc so if anyone would like me to install 14.2 and provide logs id be happy to 
the one error i was able to visualise before the app crashing is this:
![Screenshot_2024-12-04_111722](https://github.com/user-attachments/assets/34979382-f63a-428d-b8a0-1aa218f077cb)

**Environment**
 - OS: Windows 10 Pro 22H2 19045.5198
 - Device: PC
 - App Version: 14.2

**Comment by United600** [comment] 2024-12-04 13:52
The use of a Windows 11-only property made that version crash on Windows 10. An update addressing the issue is now live in the store. Let us know if it fixed your issue.
I apologize for the oversight

**Comment by RoyceThomas** [comment] 2024-12-06 05:10
no need to apologise. happy that it was located quickly and i can confirm that i believe it is fixed now.

**Comment by United600** [comment] 2024-12-06 15:52
Happy to hear, can you close the issue?

>no need to apologise

Well, an unnecessary mistake on my part resulted in the possible worst-case scenario on Windows 10.

**Comment by huynhsontung** [comment] 2024-12-06 20:49
Closing as it should be fixed in v0.14.3

**Closed by huynhsontung** 2024-12-06 20:49 UTC
Labels: bug
