### ISSUE TITLE
Bad audio quality (audio saturation)

### ISSUE THREAD

**Issue by Mitia99** [huynhsontung/Screenbox#230] opened 2023-11-14 11:22 UTC
**Describe the bug**
Bad audio quality (audio saturation)

**How To Reproduce**
1. Set system volume to 60% and Screenbox volume to 100% (to well notice the bad quality on Screenbox)
2. Play a video
3. Compare the audio quality with [Windows Media player](https://apps.microsoft.com/detail/windows-media-player/9WZDNCRFJ3PT?hl=en-US&gl=US)

**Expected behavior**
Good audio quality

**Environment**

 - OS: Windows 11 23H2 Latest stable
 - Device: Huawei Matebook E 2022
 - App Version 0.10.1

**Additional context**
There is no specific media to reproduce the issue but for more context I usually play video which have these audio details:
- `Bit rate` 128 kbps
- `Channels` 2 (stereo)
- `Audio sample rate` 44.100 kHz

Thanks for investigating,

**Comment by huynhsontung** [comment] 2023-11-14 16:10
Hello, can you also confirm if the same problem occurs in VLC media player?

**Comment by huynhsontung** [comment] 2023-11-14 18:49
I can't reproduce this issue on my end. Can you try again with [VLC UWP](https://apps.microsoft.com/detail/vlc-uwp/9NBLGGH4VVNH)?

I would appreciate it if you can answer the following questions for more context:
- Is this a consistent issue?
- Does it happen with every file or only specific files?
- Is there a difference between audio only files and video files?
- What kind of output device experiences this issue? Speaker, headphones, Bluetooth headphones, or all of them?
- Do you have advanced mode enabled? (you can check in the app settings)

**Comment by Mitia99** [comment] 2023-11-15 05:52
I tried with [VLC UWP](https://apps.microsoft.com/detail/vlc-uwp/9NBLGGH4VVNH) and there was no issue.

**Is this a consistent issue?**
Yes

**Does it happen with every file or only specific files?**
Not sure but most of. 
[Here](https://file.io/4tpkjTzHia7S)'s a file I uploaded. Hope that you can reproduce the issue.

**Is there a difference between audio only files and video files?**
Same issue with MP3

**What kind of output device experiences this issue?**
All of them

**Do you have advanced mode enabled?**
No advanced setting.
No volume boost.

**Comment by huynhsontung** [comment] 2023-11-15 08:41
Thank you for answering. Confirmed I can reproduce it with the file you provided. I will investigate this issue further and update here when I have more info.

**Comment by huynhsontung** [comment] 2023-11-27 06:21
The issue was confirmed to originate from LivVLC. I have downgraded the LibVLC version as a workaround. This issue should be fixed in Screenbox v0.10.2. @Mitia99 please confirm again if possible. Thank you.

Tracking LibVLC issue: https://code.videolan.org/videolan/libvlc-nuget/-/issues/24

**Comment by Mitia99** [comment] 2023-11-27 06:28
> The issue was confirmed to originate from LivVLC. I have downgraded the LibVLC version as a workaround. This issue should be fixed in Screenbox v0.10.2. @Mitia99 please confirm again if possible. Thank you.
> 
> Tracking LibVLC issue: https://code.videolan.org/videolan/libvlc-nuget/-/issues/24

Indeed. I downloaded latest screenbox version and the audio issue was fixed.

Thanks for reporting to LibVLC.

**Closed** 2023-11-27 07:26 UTC
Labels: bug
